name: Apptainer Build
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  APPTAINER_VERSION: 1.2.5
  ORAS_VERSION: 1.1.0

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build Apptainer image
    permissions:
      contents: write
      packages: write
    steps:
      - name: Clear up space
        uses: easimon/maximize-build-space@master
        with:
            remove-dotnet: 'true'
            remove-android: 'true'
            remove-haskell: 'true'
            remove-codeql: 'true'
            remove-docker-images: 'true'
      - name: Install Apptainer
        with:
          apptainer-version: '1.2.5'
        uses: uw-psych/apptainer-actions/setup@main
      - name: Check out code for the container build
        uses: actions/checkout@v4
      - name: Build and push Apptainer image
        uses: uw-psych/apptainer-actions/build-and-push@main
        with:
          deffile: Singularity
          xtrace: 'true'
          apptainer-tmpdir: ${{ github.workspace }}/apptainer-tmp
          image-dir: ${{ github.workspace }}

